version: '3.3'
services:
  neo4j:
    image: neo4j:enterprise
    container_name: neo4j
    ports:
        - '7474:7474'
        - '7687:7687'
    volumes:
        - '$HOME/neo4j/data:/data'
        - '$HOME/neo4j/logs:/logs'
        - '$HOME/neo4j/conf:/conf'
        - '$HOME/neo4j/import:/var/lib/neo4j/import'
        - '$HOME/neo4j/plugins:/plugins'
    environment:
        - NEO4J_AUTH=neo4j/test
        - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
        - NEO4J_dbms_active__database=${db:-graph.db}
        - NEO4J_bloom_authorization__role=${role:-admin}